/**
 * Bundle the edge functions: supabase/functions/<name>/src.ts → index.ts, one
 * self-contained ES module with the engine and the circuits inlined, so the
 * server runs exactly the physics the game runs. Run after any engine or
 * track change, then deploy (see docs/LEADERBOARD.md).
 * Usage: npm run build:functions
 */
import { build } from "esbuild";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
for (const name of ["submit-lap"]) {
  const dir = resolve(root, "supabase/functions", name);
  const out = await build({
    entryPoints: [resolve(dir, "src.ts")],
    outfile: resolve(dir, "index.ts"),
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    minify: true,
    legalComments: "none",
    banner: { js: `// Generated by tools/functions/build.ts from src.ts. Do not edit.` },
    metafile: true,
  });
  const bytes = Object.values(out.metafile.outputs)[0].bytes;
  console.log(`${name}: ${(bytes / 1024).toFixed(0)} kB`);
}
